% EJECUCIÓN BUCLE DE CONTROL - IMPLEMENTACIÓN EN LABVIEW
%
% Este script ejecuta una iteración del bucle de control y obtiene una
% acción de control óptima

import casadi.*

%% ========================================================================
%% ESTIMACIÓN DE ESTADOS Y OPTIMIZACIÓN DE CONTROL
%% ========================================================================

tic

% Estimación de estados mediante MHE
[v_est_seq, x_est_k, u_est_k, lam_g_est, lam_x_est, ...
     y_meas_buff, u_buff, status_est_k, n_iter_est_k] = estimar_estado(N_e, solver_mhe, v_est_seq, lam_g_est, lam_x_est, ...
                                                                       v_est_min, v_est_max, ...
                                                                       g_est_min, g_est_max, ...
                                                                       y_meas_buff, y_meas_k, ...
                                                                       u_buff, u_meas_k, u_resist);

% Optimización de control mediante MPC
[u_ctrl_seq, u_ctrl_k, x_pred, ...
     lam_g_ctrl, lam_x_ctrl, status_ctrl_k, n_iter_ctrl_k] = optimizar_control(solver_mpc, u_ctrl_seq, lam_g_ctrl, lam_x_ctrl, ...
                                                                               u_ctrl_min, u_ctrl_max, ...
                                                                               g_ctrl_min, g_ctrl_max, ...
                                                                               x_est_k, u_k, u_resist, ...
                                                                               ref_k, x_pred, y_meas_k, ...
                                                                               simulador_mpc, w_track, R_ctrl, param_modelo_ctrl);
    
t_k = toc;

% Acción de control obtenida
u_k = u_ctrl_k;